[project]
name = "saunachimp"
version = "0.0.1"
requires-python = "==3.10.9"
dependencies = [
    "aiomysql",
    "asyncio",
    "cryptography",
    "fastapi",
    "openai",
    "uvicorn",
    "pandas"
]